version: "3.7"

services:
  balanceador:
    image: haproxy:latest
    networks:
      - red_interna
    ports:
      - "443:443"
      - "8404:8404"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  web1:
    build: app1/.
    expose:
      - "8443"
    networks:
      - red_interna
    links:
     - db
     - servicio_interno
    environment:
     - SPRING_DATASOURCE_URL=jdbc:mysql://db/toko

  web2:
    build: app1/.
    expose:
      - "8443"
    networks:
      - red_interna
    links:
     - db
     - servicio_interno
    environment:
     - SPRING_DATASOURCE_URL=jdbc:mysql://db/toko
  db:
    image: mysql:latest
    expose:
      - "3306"
    networks:
      - red_interna
    volumes:
      - mysql-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=darwin
      - MYSQL_DATABASE=toko
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123456

  servicio_interno:
    build: app2/.
    expose:
      - "8000"
    networks:
      - red_interna
    links:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/toko
  servicio_interno2:
    build: app2/.
    expose:
      - "8000"
    networks:
      - red_interna
    links:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/toko
networks:
  red_interna:
    driver: bridge
volumes:
  mysql-db-data:
